export const NOTIFICATION_TYPES = {
  LOW_STOCK: "LOW_STOCK",
  NEAR_EXPIRY: "NEAR_EXPIRY",
  EXPIRED: "EXPIRED",
  SUPPLY_REQUEST: "SUPPLY_REQUEST",
  SHIPMENT: "SHIPMENT",
  PURCHASE_REQUEST: "PURCHASE_REQUEST",
};

export const NOTIFICATION_TYPE_VALUES = Object.values(NOTIFICATION_TYPES);

export const NOTIFICATION_STATUSES = {
  UNREAD: "UNREAD",
  READ: "READ",
};

export const NOTIFICATION_STATUS_VALUES = Object.values(NOTIFICATION_STATUSES);

export const NOTIFICATION_CHANNELS = {
  IN_APP: "IN_APP",
  SMS: "SMS",
};

export const NOTIFICATION_CHANNEL_VALUES = Object.values(NOTIFICATION_CHANNELS);

export const DEFAULT_EXPIRY_ALERT_DAYS = Number(
  process.env.EXPIRY_ALERT_DAYS ?? 30,
);

export const AUDIT_LOG_RETENTION_DAYS = Number(
  process.env.AUDIT_LOG_RETENTION_DAYS ?? 90,
);

export const AUDIT_LOG_RETENTION_SECONDS = AUDIT_LOG_RETENTION_DAYS * 24 * 60 * 60;
