import { ROLES } from "./roles.js";

export const PERMISSIONS = {
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DEACTIVATE: "users.deactivate",
  PERMISSIONS_READ: "permissions.read",
  WAREHOUSES_READ: "warehouses.read",
  WAREHOUSES_CREATE: "warehouses.create",
  WAREHOUSES_UPDATE: "warehouses.update",
  WAREHOUSES_DEACTIVATE: "warehouses.deactivate",
  PHARMACIES_READ: "pharmacies.read",
  PHARMACIES_CREATE: "pharmacies.create",
  PHARMACIES_UPDATE: "pharmacies.update",
  PHARMACIES_DEACTIVATE: "pharmacies.deactivate",
  CATEGORIES_READ: "categories.read",
  CATEGORIES_CREATE: "categories.create",
  CATEGORIES_UPDATE: "categories.update",
  CATEGORIES_DEACTIVATE: "categories.deactivate",
  MANUFACTURERS_READ: "manufacturers.read",
  MANUFACTURERS_CREATE: "manufacturers.create",
  MANUFACTURERS_UPDATE: "manufacturers.update",
  MANUFACTURERS_DEACTIVATE: "manufacturers.deactivate",
  ACTIVE_INGREDIENTS_READ: "activeIngredients.read",
  ACTIVE_INGREDIENTS_CREATE: "activeIngredients.create",
  ACTIVE_INGREDIENTS_UPDATE: "activeIngredients.update",
  ACTIVE_INGREDIENTS_DEACTIVATE: "activeIngredients.deactivate",
  DRUGS_READ: "drugs.read",
  DRUGS_CREATE: "drugs.create",
  DRUGS_UPDATE: "drugs.update",
  DRUGS_DEACTIVATE: "drugs.deactivate",
  BATCHES_READ: "batches.read",
  BATCHES_CREATE: "batches.create",
  BATCHES_UPDATE: "batches.update",
  BATCHES_DEACTIVATE: "batches.deactivate",
  INVENTORY_READ: "inventory.read",
  STOCK_MOVEMENTS_READ: "stockMovements.read",
  STOCK_MOVEMENTS_CREATE: "stockMovements.create",
  SUPPLY_REQUESTS_READ: "supplyRequests.read",
  SUPPLY_REQUESTS_CREATE: "supplyRequests.create",
  SUPPLY_REQUESTS_APPROVE: "supplyRequests.approve",
  SUPPLY_REQUESTS_CANCEL: "supplyRequests.cancel",
  SHIPMENTS_READ: "shipments.read",
  SHIPMENTS_CREATE: "shipments.create",
  SHIPMENTS_SEND: "shipments.send",
  SHIPMENTS_RECEIVE: "shipments.receive",
  SUPPLIERS_READ: "suppliers.read",
  SUPPLIERS_CREATE: "suppliers.create",
  SUPPLIERS_UPDATE: "suppliers.update",
  SUPPLIERS_DEACTIVATE: "suppliers.deactivate",
  PURCHASE_REQUESTS_READ: "purchaseRequests.read",
  PURCHASE_REQUESTS_CREATE: "purchaseRequests.create",
  PURCHASE_REQUESTS_APPROVE: "purchaseRequests.approve",
  PURCHASE_REQUESTS_CANCEL: "purchaseRequests.cancel",
  PURCHASE_ORDERS_READ: "purchaseOrders.read",
  PURCHASE_RECEIPTS_READ: "purchaseReceipts.read",
  PURCHASE_RECEIPTS_CREATE: "purchaseReceipts.create",
  PURCHASE_INVOICES_READ: "purchaseInvoices.read",
  PAYMENT_METHODS_READ: "paymentMethods.read",
  PAYMENT_METHODS_CREATE: "paymentMethods.create",
  PAYMENT_METHODS_UPDATE: "paymentMethods.update",
  PAYMENT_METHODS_DEACTIVATE: "paymentMethods.deactivate",
  DRUGS_UPDATE_PRICE: "drugs.updatePrice",
  SALES_INVOICES_READ: "salesInvoices.read",
  SALES_INVOICES_CREATE: "salesInvoices.create",
  SALES_APPLY_DISCOUNT: "sales.applyDiscount",
  INVENTORY_ADJUSTMENTS_READ: "inventoryAdjustments.read",
  INVENTORY_ADJUSTMENTS_CREATE: "inventoryAdjustments.create",
  DESTRUCTIONS_READ: "destructions.read",
  DESTRUCTIONS_CREATE: "destructions.create",
  CUSTOMER_RETURNS_READ: "customerReturns.read",
  CUSTOMER_RETURNS_CREATE: "customerReturns.create",
  PHARMACY_RETURNS_READ: "pharmacyReturns.read",
  PHARMACY_RETURNS_CREATE: "pharmacyReturns.create",
  PHARMACY_RETURNS_SEND: "pharmacyReturns.send",
  PHARMACY_RETURNS_RECEIVE: "pharmacyReturns.receive",
  SUPPLIER_RETURNS_READ: "supplierReturns.read",
  SUPPLIER_RETURNS_CREATE: "supplierReturns.create",
  AUDIT_LOGS_READ: "auditLogs.read",
  NOTIFICATIONS_READ: "notifications.read",
  NOTIFICATIONS_UPDATE: "notifications.update",
  NOTIFICATIONS_RUN_ALERTS: "notifications.runAlerts",
  REPORTS_READ: "reports.read",
};

export const PERMISSION_VALUES = Object.values(PERMISSIONS);

const ALL_PERMISSIONS = PERMISSION_VALUES;

const CATALOG_READ = [
  PERMISSIONS.CATEGORIES_READ,
  PERMISSIONS.MANUFACTURERS_READ,
  PERMISSIONS.ACTIVE_INGREDIENTS_READ,
  PERMISSIONS.DRUGS_READ,
];

const CATALOG_MANAGE = [
  ...CATALOG_READ,
  PERMISSIONS.CATEGORIES_CREATE,
  PERMISSIONS.CATEGORIES_UPDATE,
  PERMISSIONS.CATEGORIES_DEACTIVATE,
  PERMISSIONS.MANUFACTURERS_CREATE,
  PERMISSIONS.MANUFACTURERS_UPDATE,
  PERMISSIONS.MANUFACTURERS_DEACTIVATE,
  PERMISSIONS.ACTIVE_INGREDIENTS_CREATE,
  PERMISSIONS.ACTIVE_INGREDIENTS_UPDATE,
  PERMISSIONS.ACTIVE_INGREDIENTS_DEACTIVATE,
  PERMISSIONS.DRUGS_CREATE,
  PERMISSIONS.DRUGS_UPDATE,
  PERMISSIONS.DRUGS_DEACTIVATE,
];

const BATCHES_READ = [PERMISSIONS.BATCHES_READ];

const BATCHES_MANAGE = [
  ...BATCHES_READ,
  PERMISSIONS.BATCHES_CREATE,
  PERMISSIONS.BATCHES_UPDATE,
  PERMISSIONS.BATCHES_DEACTIVATE,
];

const INVENTORY_READ = [PERMISSIONS.INVENTORY_READ];

const STOCK_READ = [PERMISSIONS.STOCK_MOVEMENTS_READ];

const STOCK_MANAGE = [
  ...STOCK_READ,
  PERMISSIONS.STOCK_MOVEMENTS_CREATE,
];

const INVENTORY_STOCK_READ = [...INVENTORY_READ, ...STOCK_READ];

const INVENTORY_STOCK_MANAGE = [
  ...INVENTORY_READ,
  ...STOCK_MANAGE,
];

const SUPPLY_READ = [
  PERMISSIONS.SUPPLY_REQUESTS_READ,
  PERMISSIONS.SHIPMENTS_READ,
];

const SUPPLY_PHARMACY = [
  ...SUPPLY_READ,
  PERMISSIONS.SUPPLY_REQUESTS_CREATE,
  PERMISSIONS.SUPPLY_REQUESTS_CANCEL,
  PERMISSIONS.SHIPMENTS_RECEIVE,
];

const SUPPLY_WAREHOUSE = [
  ...SUPPLY_READ,
  PERMISSIONS.SUPPLY_REQUESTS_CREATE,
  PERMISSIONS.SUPPLY_REQUESTS_CANCEL,
  PERMISSIONS.SHIPMENTS_CREATE,
  PERMISSIONS.SHIPMENTS_SEND,
  PERMISSIONS.SHIPMENTS_RECEIVE,
];

const SUPPLY_MANAGE = [
  ...SUPPLY_READ,
  PERMISSIONS.SUPPLY_REQUESTS_CREATE,
  PERMISSIONS.SUPPLY_REQUESTS_APPROVE,
  PERMISSIONS.SUPPLY_REQUESTS_CANCEL,
  PERMISSIONS.SHIPMENTS_CREATE,
  PERMISSIONS.SHIPMENTS_SEND,
  PERMISSIONS.SHIPMENTS_RECEIVE,
];

const SUPPLIERS_MANAGE = [
  PERMISSIONS.SUPPLIERS_READ,
  PERMISSIONS.SUPPLIERS_CREATE,
  PERMISSIONS.SUPPLIERS_UPDATE,
  PERMISSIONS.SUPPLIERS_DEACTIVATE,
];

const PURCHASE_READ = [
  PERMISSIONS.SUPPLIERS_READ,
  PERMISSIONS.PURCHASE_REQUESTS_READ,
  PERMISSIONS.PURCHASE_ORDERS_READ,
  PERMISSIONS.PURCHASE_RECEIPTS_READ,
  PERMISSIONS.PURCHASE_INVOICES_READ,
];

const PURCHASE_WAREHOUSE = [
  ...PURCHASE_READ,
  PERMISSIONS.PURCHASE_REQUESTS_CREATE,
  PERMISSIONS.PURCHASE_REQUESTS_CANCEL,
  PERMISSIONS.PURCHASE_RECEIPTS_CREATE,
];

const PURCHASE_MANAGE = [
  ...PURCHASE_READ,
  ...SUPPLIERS_MANAGE,
  PERMISSIONS.PURCHASE_REQUESTS_CREATE,
  PERMISSIONS.PURCHASE_REQUESTS_APPROVE,
  PERMISSIONS.PURCHASE_REQUESTS_CANCEL,
  PERMISSIONS.PURCHASE_RECEIPTS_CREATE,
];

const SALES_READ = [
  PERMISSIONS.PAYMENT_METHODS_READ,
  PERMISSIONS.SALES_INVOICES_READ,
];

const SALES_PHARMACY = [
  ...SALES_READ,
  PERMISSIONS.SALES_INVOICES_CREATE,
];

const SALES_MANAGE = [
  ...SALES_PHARMACY,
  PERMISSIONS.DRUGS_UPDATE_PRICE,
  PERMISSIONS.SALES_APPLY_DISCOUNT,
];

const RETURNS_PHARMACY_READ = [
  PERMISSIONS.CUSTOMER_RETURNS_READ,
  PERMISSIONS.PHARMACY_RETURNS_READ,
  PERMISSIONS.DESTRUCTIONS_READ,
  PERMISSIONS.INVENTORY_ADJUSTMENTS_READ,
];

const RETURNS_PHARMACY = [
  ...RETURNS_PHARMACY_READ,
  PERMISSIONS.CUSTOMER_RETURNS_CREATE,
  PERMISSIONS.PHARMACY_RETURNS_CREATE,
  PERMISSIONS.PHARMACY_RETURNS_SEND,
  PERMISSIONS.DESTRUCTIONS_CREATE,
];

const RETURNS_PHARMACY_MANAGE = [
  ...RETURNS_PHARMACY,
  PERMISSIONS.PHARMACY_RETURNS_RECEIVE,
  PERMISSIONS.INVENTORY_ADJUSTMENTS_CREATE,
];

const RETURNS_WAREHOUSE_READ = [
  PERMISSIONS.SUPPLIER_RETURNS_READ,
  PERMISSIONS.PHARMACY_RETURNS_READ,
  PERMISSIONS.DESTRUCTIONS_READ,
  PERMISSIONS.INVENTORY_ADJUSTMENTS_READ,
];

const RETURNS_WAREHOUSE = [
  ...RETURNS_WAREHOUSE_READ,
  PERMISSIONS.SUPPLIER_RETURNS_CREATE,
  PERMISSIONS.PHARMACY_RETURNS_RECEIVE,
  PERMISSIONS.DESTRUCTIONS_CREATE,
];

const RETURNS_WAREHOUSE_MANAGE = [
  ...RETURNS_WAREHOUSE,
  PERMISSIONS.INVENTORY_ADJUSTMENTS_CREATE,
];

const NOTIFICATIONS_BASIC = [
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_UPDATE,
];

const AUDIT_AND_ALERTS_MANAGE = [
  PERMISSIONS.AUDIT_LOGS_READ,
  PERMISSIONS.NOTIFICATIONS_RUN_ALERTS,
];

const REPORTS_READ = [PERMISSIONS.REPORTS_READ];

const ROLE_PERMISSIONS = {
  [ROLES.SYSTEM_ADMIN]: ALL_PERMISSIONS,
  [ROLES.PHARMACY_ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.PERMISSIONS_READ,
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.WAREHOUSES_UPDATE,
    PERMISSIONS.PHARMACIES_READ,
    PERMISSIONS.PHARMACIES_UPDATE,
    ...CATALOG_MANAGE,
    PERMISSIONS.DRUGS_UPDATE_PRICE,
    ...BATCHES_MANAGE,
    ...INVENTORY_STOCK_MANAGE,
    ...SUPPLY_MANAGE,
    ...PURCHASE_MANAGE,
    ...SALES_MANAGE,
    ...RETURNS_PHARMACY_MANAGE,
    ...NOTIFICATIONS_BASIC,
    ...AUDIT_AND_ALERTS_MANAGE,
    ...REPORTS_READ,
  ],
  [ROLES.PHARMACY_MANAGER]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.PHARMACIES_READ,
    PERMISSIONS.PHARMACIES_UPDATE,
    ...CATALOG_READ,
    PERMISSIONS.DRUGS_UPDATE_PRICE,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_MANAGE,
    ...SUPPLY_MANAGE,
    ...PURCHASE_READ,
    ...SALES_MANAGE,
    ...RETURNS_PHARMACY_MANAGE,
    ...NOTIFICATIONS_BASIC,
    ...AUDIT_AND_ALERTS_MANAGE,
    ...REPORTS_READ,
  ],
  [ROLES.WAREHOUSE_MANAGER]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.WAREHOUSES_UPDATE,
    ...CATALOG_READ,
    PERMISSIONS.BATCHES_READ,
    PERMISSIONS.BATCHES_CREATE,
    PERMISSIONS.BATCHES_UPDATE,
    ...INVENTORY_STOCK_MANAGE,
    ...SUPPLY_MANAGE,
    ...PURCHASE_MANAGE,
    ...RETURNS_WAREHOUSE_MANAGE,
    ...NOTIFICATIONS_BASIC,
    ...AUDIT_AND_ALERTS_MANAGE,
    ...REPORTS_READ,
  ],
  [ROLES.PHARMACIST]: [
    PERMISSIONS.ACTIVE_INGREDIENTS_READ,
    PERMISSIONS.DRUGS_READ,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_READ,
    ...SUPPLY_READ,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.PURCHASE_ORDERS_READ,
    ...SALES_PHARMACY,
    ...RETURNS_PHARMACY,
    ...NOTIFICATIONS_BASIC,
  ],
  [ROLES.PHARMACY_EMPLOYEE]: [
    PERMISSIONS.DRUGS_READ,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_READ,
    ...SUPPLY_PHARMACY,
    ...SALES_PHARMACY,
    ...RETURNS_PHARMACY,
    ...NOTIFICATIONS_BASIC,
  ],
  [ROLES.WAREHOUSE_EMPLOYEE]: [
    PERMISSIONS.DRUGS_READ,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_READ,
    ...SUPPLY_WAREHOUSE,
    ...PURCHASE_WAREHOUSE,
    ...RETURNS_WAREHOUSE,
    ...NOTIFICATIONS_BASIC,
  ],
};

export const getPermissionsForRole = (role) => ROLE_PERMISSIONS[role] ?? [];

export const hasPermission = (role, permission) =>
  getPermissionsForRole(role).includes(permission);
