import { ROLES } from "./roles.js";

export const PERMISSIONS = {
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DEACTIVATE: "users.deactivate",
  PERMISSIONS_READ: "permissions.read",
  WAREHOUSES_READ: "warehouses.read",
  WAREHOUSES_CREATE: "warehouses.create",
  WAREHOUSES_UPDATE: "warehouses.update",
  WAREHOUSES_DEACTIVATE: "warehouses.deactivate",
  PHARMACIES_READ: "pharmacies.read",
  PHARMACIES_CREATE: "pharmacies.create",
  PHARMACIES_UPDATE: "pharmacies.update",
  PHARMACIES_DEACTIVATE: "pharmacies.deactivate",
  CATEGORIES_READ: "categories.read",
  CATEGORIES_CREATE: "categories.create",
  CATEGORIES_UPDATE: "categories.update",
  CATEGORIES_DEACTIVATE: "categories.deactivate",
  MANUFACTURERS_READ: "manufacturers.read",
  MANUFACTURERS_CREATE: "manufacturers.create",
  MANUFACTURERS_UPDATE: "manufacturers.update",
  MANUFACTURERS_DEACTIVATE: "manufacturers.deactivate",
  ACTIVE_INGREDIENTS_READ: "activeIngredients.read",
  ACTIVE_INGREDIENTS_CREATE: "activeIngredients.create",
  ACTIVE_INGREDIENTS_UPDATE: "activeIngredients.update",
  ACTIVE_INGREDIENTS_DEACTIVATE: "activeIngredients.deactivate",
  DRUGS_READ: "drugs.read",
  DRUGS_CREATE: "drugs.create",
  DRUGS_UPDATE: "drugs.update",
  DRUGS_DEACTIVATE: "drugs.deactivate",
  BATCHES_READ: "batches.read",
  BATCHES_CREATE: "batches.create",
  BATCHES_UPDATE: "batches.update",
  BATCHES_DEACTIVATE: "batches.deactivate",
  INVENTORY_READ: "inventory.read",
  STOCK_MOVEMENTS_READ: "stockMovements.read",
  STOCK_MOVEMENTS_CREATE: "stockMovements.create",
  SUPPLY_REQUESTS_READ: "supplyRequests.read",
  SUPPLY_REQUESTS_CREATE: "supplyRequests.create",
  SUPPLY_REQUESTS_APPROVE: "supplyRequests.approve",
  SUPPLY_REQUESTS_CANCEL: "supplyRequests.cancel",
  SHIPMENTS_READ: "shipments.read",
  SHIPMENTS_CREATE: "shipments.create",
  SHIPMENTS_SEND: "shipments.send",
  SHIPMENTS_RECEIVE: "shipments.receive",
};

export const PERMISSION_VALUES = Object.values(PERMISSIONS);

const ALL_PERMISSIONS = PERMISSION_VALUES;

const CATALOG_READ = [
  PERMISSIONS.CATEGORIES_READ,
  PERMISSIONS.MANUFACTURERS_READ,
  PERMISSIONS.ACTIVE_INGREDIENTS_READ,
  PERMISSIONS.DRUGS_READ,
];

const CATALOG_MANAGE = [
  ...CATALOG_READ,
  PERMISSIONS.CATEGORIES_CREATE,
  PERMISSIONS.CATEGORIES_UPDATE,
  PERMISSIONS.CATEGORIES_DEACTIVATE,
  PERMISSIONS.MANUFACTURERS_CREATE,
  PERMISSIONS.MANUFACTURERS_UPDATE,
  PERMISSIONS.MANUFACTURERS_DEACTIVATE,
  PERMISSIONS.ACTIVE_INGREDIENTS_CREATE,
  PERMISSIONS.ACTIVE_INGREDIENTS_UPDATE,
  PERMISSIONS.ACTIVE_INGREDIENTS_DEACTIVATE,
  PERMISSIONS.DRUGS_CREATE,
  PERMISSIONS.DRUGS_UPDATE,
  PERMISSIONS.DRUGS_DEACTIVATE,
];

const BATCHES_READ = [PERMISSIONS.BATCHES_READ];

const BATCHES_MANAGE = [
  ...BATCHES_READ,
  PERMISSIONS.BATCHES_CREATE,
  PERMISSIONS.BATCHES_UPDATE,
  PERMISSIONS.BATCHES_DEACTIVATE,
];

const INVENTORY_READ = [PERMISSIONS.INVENTORY_READ];

const STOCK_READ = [PERMISSIONS.STOCK_MOVEMENTS_READ];

const STOCK_MANAGE = [
  ...STOCK_READ,
  PERMISSIONS.STOCK_MOVEMENTS_CREATE,
];

const INVENTORY_STOCK_READ = [...INVENTORY_READ, ...STOCK_READ];

const INVENTORY_STOCK_MANAGE = [
  ...INVENTORY_READ,
  ...STOCK_MANAGE,
];

const SUPPLY_READ = [
  PERMISSIONS.SUPPLY_REQUESTS_READ,
  PERMISSIONS.SHIPMENTS_READ,
];

const SUPPLY_PHARMACY = [
  ...SUPPLY_READ,
  PERMISSIONS.SUPPLY_REQUESTS_CREATE,
  PERMISSIONS.SUPPLY_REQUESTS_CANCEL,
  PERMISSIONS.SHIPMENTS_RECEIVE,
];

const SUPPLY_WAREHOUSE = [
  ...SUPPLY_READ,
  PERMISSIONS.SUPPLY_REQUESTS_CREATE,
  PERMISSIONS.SUPPLY_REQUESTS_CANCEL,
  PERMISSIONS.SHIPMENTS_CREATE,
  PERMISSIONS.SHIPMENTS_SEND,
  PERMISSIONS.SHIPMENTS_RECEIVE,
];

const SUPPLY_MANAGE = [
  ...SUPPLY_READ,
  PERMISSIONS.SUPPLY_REQUESTS_CREATE,
  PERMISSIONS.SUPPLY_REQUESTS_APPROVE,
  PERMISSIONS.SUPPLY_REQUESTS_CANCEL,
  PERMISSIONS.SHIPMENTS_CREATE,
  PERMISSIONS.SHIPMENTS_SEND,
  PERMISSIONS.SHIPMENTS_RECEIVE,
];

const ROLE_PERMISSIONS = {
  [ROLES.SYSTEM_ADMIN]: ALL_PERMISSIONS,
  [ROLES.PHARMACY_ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.PERMISSIONS_READ,
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.WAREHOUSES_UPDATE,
    PERMISSIONS.PHARMACIES_READ,
    PERMISSIONS.PHARMACIES_UPDATE,
    ...CATALOG_MANAGE,
    ...BATCHES_MANAGE,
    ...INVENTORY_STOCK_MANAGE,
    ...SUPPLY_MANAGE,
  ],
  [ROLES.PHARMACY_MANAGER]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.PHARMACIES_READ,
    PERMISSIONS.PHARMACIES_UPDATE,
    ...CATALOG_READ,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_MANAGE,
    ...SUPPLY_MANAGE,
  ],
  [ROLES.WAREHOUSE_MANAGER]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.WAREHOUSES_UPDATE,
    ...CATALOG_READ,
    PERMISSIONS.BATCHES_READ,
    PERMISSIONS.BATCHES_CREATE,
    PERMISSIONS.BATCHES_UPDATE,
    ...INVENTORY_STOCK_MANAGE,
    ...SUPPLY_MANAGE,
  ],
  [ROLES.PHARMACIST]: [
    PERMISSIONS.ACTIVE_INGREDIENTS_READ,
    PERMISSIONS.DRUGS_READ,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_READ,
    ...SUPPLY_READ,
  ],
  [ROLES.PHARMACY_EMPLOYEE]: [
    PERMISSIONS.DRUGS_READ,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_READ,
    ...SUPPLY_PHARMACY,
  ],
  [ROLES.WAREHOUSE_EMPLOYEE]: [
    PERMISSIONS.DRUGS_READ,
    ...BATCHES_READ,
    ...INVENTORY_STOCK_READ,
    ...SUPPLY_WAREHOUSE,
  ],
};

export const getPermissionsForRole = (role) => ROLE_PERMISSIONS[role] ?? [];

export const hasPermission = (role, permission) =>
  getPermissionsForRole(role).includes(permission);
