export const PHARMACY_RETURN_STATUSES = {
  PREPARED: "PREPARED",
  SENT: "SENT",
  PARTIALLY_RECEIVED: "PARTIALLY_RECEIVED",
  RECEIVED: "RECEIVED",
};

export const PHARMACY_RETURN_STATUS_VALUES = Object.values(
  PHARMACY_RETURN_STATUSES,
);
