export const PURCHASE_ORDER_STATUSES = {
  OPEN: "OPEN",
  PARTIALLY_RECEIVED: "PARTIALLY_RECEIVED",
  RECEIVED: "RECEIVED",
};

export const PURCHASE_ORDER_STATUS_VALUES = Object.values(PURCHASE_ORDER_STATUSES);
