export const PURCHASE_REQUEST_STATUSES = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

export const PURCHASE_REQUEST_STATUS_VALUES = Object.values(
  PURCHASE_REQUEST_STATUSES,
);
