export const ROLES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  PHARMACY_ADMIN: "PHARMACY_ADMIN",
  PHARMACY_MANAGER: "PHARMACY_MANAGER",
  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER",
  PHARMACIST: "PHARMACIST",
  PHARMACY_EMPLOYEE: "PHARMACY_EMPLOYEE",
  WAREHOUSE_EMPLOYEE: "WAREHOUSE_EMPLOYEE",
};

export const ROLE_VALUES = Object.values(ROLES);
