export const SHIPMENT_STATUSES = {
  PREPARED: "PREPARED",
  SENT: "SENT",
  PARTIALLY_RECEIVED: "PARTIALLY_RECEIVED",
  RECEIVED: "RECEIVED",
};

export const SHIPMENT_STATUS_VALUES = Object.values(SHIPMENT_STATUSES);
