export const LOCATION_TYPES = {
  PHARMACY: "pharmacy",
  WAREHOUSE: "warehouse",
};

export const LOCATION_TYPE_VALUES = Object.values(LOCATION_TYPES);

export const MOVEMENT_DIRECTIONS = {
  IN: "in",
  OUT: "out",
};

export const MOVEMENT_DIRECTION_VALUES = Object.values(MOVEMENT_DIRECTIONS);

export const MOVEMENT_TYPES = {
  PURCHASE_RECEIVING: "PURCHASE_RECEIVING",
  SUPPLY_TO_PHARMACY: "SUPPLY_TO_PHARMACY",
  SUPPLY_TO_WAREHOUSE: "SUPPLY_TO_WAREHOUSE",
  RETURN_FROM_PHARMACY: "RETURN_FROM_PHARMACY",
  RETURN_TO_SUPPLIER: "RETURN_TO_SUPPLIER",
  SUPPLY_RECEIVING: "SUPPLY_RECEIVING",
  SALE: "SALE",
  CUSTOMER_RETURN: "CUSTOMER_RETURN",
  RETURN_TO_WAREHOUSE: "RETURN_TO_WAREHOUSE",
  DESTRUCTION: "DESTRUCTION",
  INVENTORY_ADJUSTMENT: "INVENTORY_ADJUSTMENT",
};

export const MOVEMENT_TYPE_VALUES = Object.values(MOVEMENT_TYPES);
