export const SUPPLY_REQUEST_TYPES = {
  PHARMACY_TO_WAREHOUSE: "PHARMACY_TO_WAREHOUSE",
  WAREHOUSE_TO_WAREHOUSE: "WAREHOUSE_TO_WAREHOUSE",
};

export const SUPPLY_REQUEST_TYPE_VALUES = Object.values(SUPPLY_REQUEST_TYPES);

export const SUPPLY_REQUEST_STATUSES = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

export const SUPPLY_REQUEST_STATUS_VALUES = Object.values(SUPPLY_REQUEST_STATUSES);
